### PR TITLE
feat: support arm64 linux & use maturin

### PR DESCRIPTION
**Pull request by Mokto**

### CODE REVIEW

**Comment by wseaton** [comment]
Thanks @Mokto, definitely interested in merging this. Let me have a look if anything else needs to change as part of a version bump.

**Comment by wseaton** [comment]
Looks like https://github.com/sqlparser-rs/sqlparser-rs/commit/8dbcbb3c277d81968b0843b03545de958ac9d2ef needs to be added, are you interested in helping sneak that change in w/ the update?

**Comment by Mokto** [comment]
You can check it now.

If I did it right if you merge this and create a tag it should deploy the new version.

I'm not sure how you take care of changelogs & version bumps at the moment.

**Comment by Mokto** [comment]
Whenever the new version is deployed I'll double check it in my repository ;)

**Pull request merged**
